sudo: required
language: python
python:
  - "3.5"

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  - sudo apt-get install -y build-essential wget git python3-pip python3-cffi
  - pip install -U pip setuptools
  - pip install Sphinx
  - pip install sphinx_rtd_theme
  - pip install ghp_import

script:
  - python setup.py install

after_success:
  - make deploy
  - cd plugin_packaging && ./build_plugin.sh && cd ..

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "plugin_packaging/linkSHARK_plugin.tar"
  skip_cleanup: true
  on:
    repo: smartshark/linkSHARK
    tags: true
